## [2637.有时间限制的 Promise 对象 中文热门题解1](https://leetcode.cn/problems/promise-time-limit/solutions/100000/fang-zhi-zhong-fu-wu-yi-yi-diao-yong-ban-amok)

作者：[chong-hua-jia-de-xiao-tu-zi](https://leetcode.cn/u/chong-hua-jia-de-xiao-tu-zi)

刚开始没想到leetcode自动处理了返回结果，我想了半天怎么处理返回结果，里面的time怎么拿到的。是我太菜了，没想到官方处理好了。

## 解题思路
用 promise.race 实现，这个不用过多解释。

## 我的思考
因为用settimeout 模拟了超时情况，并且没有清除定时器，会导致无论结果怎么样，都会执行一次定时器。所以应该在成功执行后清除定时器。promise是链式调用，then、catch不用特殊处理，会自动到下一层，中间加了一层then对结果不会有影响。
如果是写业务的过程中，我觉得应该加上这个，保证状态的唯一不变性，可能会避免一些bug。之前做一个任务队列的需求，类似于这个做法，兜底做了任务执行的超时处理，本来任务执行成功，状态已经是ok了，因为中间跨语言调用传输耗时不稳定问题，导致可能会有某些任务状态异常，血的教训。所以这些小细节的异常处理我觉得还是有些必要的。

```
type Fn = (...params: any[]) => Promise<any>;

function timeLimit(fn: Fn, t: number): Fn {
	return async function(...args) {
        let timer;
        const timeoutPromise = new Promise((res,rej) => {
            timer = setTimeout(() => rej('Time Limit Exceeded'), t)
        });

        return Promise.race([fn(...args),timeoutPromise]).then(res => {
            clearTimeout(timer);
            return res;
        });
    }
};

/**
 * const limited = timeLimit((t) => new Promise(res => setTimeout(res, t)), 100);
 * limited(150).catch(console.log) // "Time Limit Exceeded" at t=100ms
 */
```
